//! 转译生成的交易所适配器聚合模块(ADR-0016)。
//! 由 `scripts/gen_adapters.py` 从 ccxt 4.5.73 `describe()` 自动生成;
//! 不要手改 —— 重新运行脚本即可重建。
#![allow(clippy::too_many_arguments)]

#[cfg(feature = "alpaca")]
pub mod alpaca;
#[cfg(feature = "apex")]
pub mod apex;
#[cfg(feature = "aster")]
pub mod aster;
#[cfg(feature = "backpack")]
pub mod backpack;
#[cfg(feature = "bequant")]
pub mod bequant;
#[cfg(feature = "bigone")]
pub mod bigone;
#[cfg(feature = "binancecoinm")]
pub mod binancecoinm;
#[cfg(feature = "binanceus")]
pub mod binanceus;
#[cfg(feature = "binanceusdm")]
pub mod binanceusdm;
#[cfg(feature = "bingx")]
pub mod bingx;
#[cfg(feature = "bit2c")]
pub mod bit2c;
#[cfg(feature = "bitbank")]
pub mod bitbank;
#[cfg(feature = "bitbns")]
pub mod bitbns;
#[cfg(feature = "bitfinex")]
pub mod bitfinex;
#[cfg(feature = "bitflyer")]
pub mod bitflyer;
#[cfg(feature = "bithumb")]
pub mod bithumb;
#[cfg(feature = "bitmex")]
pub mod bitmex;
#[cfg(feature = "bitopro")]
pub mod bitopro;
#[cfg(feature = "bitrue")]
pub mod bitrue;
#[cfg(feature = "bitso")]
pub mod bitso;
#[cfg(feature = "bitstamp")]
pub mod bitstamp;
#[cfg(feature = "bitteam")]
pub mod bitteam;
#[cfg(feature = "bittrade")]
pub mod bittrade;
#[cfg(feature = "bitvavo")]
pub mod bitvavo;
#[cfg(feature = "blockchaincom")]
pub mod blockchaincom;
#[cfg(feature = "blofin")]
pub mod blofin;
#[cfg(feature = "btcbox")]
pub mod btcbox;
#[cfg(feature = "btcmarkets")]
pub mod btcmarkets;
#[cfg(feature = "btcturk")]
pub mod btcturk;
#[cfg(feature = "bullish")]
pub mod bullish;
#[cfg(feature = "bybiteu")]
pub mod bybiteu;
#[cfg(feature = "bydfi")]
pub mod bydfi;
#[cfg(feature = "cex")]
pub mod cex;
#[cfg(feature = "coinbaseexchange")]
pub mod coinbaseexchange;
#[cfg(feature = "coinbaseinternational")]
pub mod coinbaseinternational;
#[cfg(feature = "coincheck")]
pub mod coincheck;
#[cfg(feature = "coinex")]
pub mod coinex;
#[cfg(feature = "coinmate")]
pub mod coinmate;
#[cfg(feature = "coinone")]
pub mod coinone;
#[cfg(feature = "coinsph")]
pub mod coinsph;
#[cfg(feature = "coinspot")]
pub mod coinspot;
#[cfg(feature = "cryptocom")]
pub mod cryptocom;
#[cfg(feature = "cryptomus")]
pub mod cryptomus;
#[cfg(feature = "deepcoin")]
pub mod deepcoin;
#[cfg(feature = "delta")]
pub mod delta;
#[cfg(feature = "deribit")]
pub mod deribit;
#[cfg(feature = "derive")]
pub mod derive;
#[cfg(feature = "digifinex")]
pub mod digifinex;
#[cfg(feature = "dydx")]
pub mod dydx;
#[cfg(feature = "exmo")]
pub mod exmo;
#[cfg(feature = "extended")]
pub mod extended;
#[cfg(feature = "fmfwio")]
pub mod fmfwio;
#[cfg(feature = "foxbit")]
pub mod foxbit;
#[cfg(feature = "gateeu")]
pub mod gateeu;
#[cfg(feature = "gemini")]
pub mod gemini;
#[cfg(feature = "grvt")]
pub mod grvt;
#[cfg(feature = "hashkey")]
pub mod hashkey;
#[cfg(feature = "hibachi")]
pub mod hibachi;
#[cfg(feature = "hitbtc")]
pub mod hitbtc;
#[cfg(feature = "hollaex")]
pub mod hollaex;
#[cfg(feature = "independentreserve")]
pub mod independentreserve;
#[cfg(feature = "indodax")]
pub mod indodax;
#[cfg(feature = "krakenfutures")]
pub mod krakenfutures;
#[cfg(feature = "kucoinfutures")]
pub mod kucoinfutures;
#[cfg(feature = "latoken")]
pub mod latoken;
#[cfg(feature = "lbank")]
pub mod lbank;
#[cfg(feature = "lighter")]
pub mod lighter;
#[cfg(feature = "luno")]
pub mod luno;
#[cfg(feature = "mercado")]
pub mod mercado;
#[cfg(feature = "modetrade")]
pub mod modetrade;
#[cfg(feature = "mudrex")]
pub mod mudrex;
#[cfg(feature = "myokx")]
pub mod myokx;
#[cfg(feature = "nado")]
pub mod nado;
#[cfg(feature = "ndax")]
pub mod ndax;
#[cfg(feature = "okxus")]
pub mod okxus;
#[cfg(feature = "onetrading")]
pub mod onetrading;
#[cfg(feature = "p2b")]
pub mod p2b;
#[cfg(feature = "pacifica")]
pub mod pacifica;
#[cfg(feature = "paradex")]
pub mod paradex;
#[cfg(feature = "paymium")]
pub mod paymium;
#[cfg(feature = "phemex")]
pub mod phemex;
#[cfg(feature = "poloniex")]
pub mod poloniex;
#[cfg(feature = "tokocrypto")]
pub mod tokocrypto;
#[cfg(feature = "toobit")]
pub mod toobit;
#[cfg(feature = "upbit")]
pub mod upbit;
#[cfg(feature = "weex")]
pub mod weex;
#[cfg(feature = "whitebit")]
pub mod whitebit;
#[cfg(feature = "woo")]
pub mod woo;
#[cfg(feature = "woofipro")]
pub mod woofipro;
#[cfg(feature = "xt")]
pub mod xt;
#[cfg(feature = "zaif")]
pub mod zaif;
#[cfg(feature = "zebpay")]
pub mod zebpay;
#[cfg(feature = "limitless")]
pub mod limitless;
#[cfg(feature = "myriad")]
pub mod myriad;
#[cfg(feature = "opinion")]
pub mod opinion;
